[package]
name = "advanced"
version = "0.1.0"
edition = "2024"

[dependencies]
thread_local = "1.1.8"
lazy_static = "1.5.0"
futures = "0.3.31"
tokio = {version = "1.44.2",features = ["full"]}
log = "0.4.27"
flexi_logger = "0.30.1"